---
title: "Packages & Datasets"
author: "Raphael Saldanha"
---

```{r, "setup package stats"}
#| echo: false
#| message: false
library(dplyr)
library(cranlogs)
library(ggplot2)
library(ggthemes)

# Packages list
pkgs <- list(
  list(name = "nseq", start_date = "2024-05-31"),
  list(name = "zendown", start_date = "2024-04-12"),
  list(name = "zenstats", start_date = "2024-05-31"),
  list(name = "brpop", start_date = "2022-07-06"),
  list(name = "tidyrates", start_date = "2024-03-19"),
  list(name = "brclimr", start_date = "2023-03-07"),
  list(name = "microdatasus", start_date = "2024-06-16")
)

# Download stats
logs <- tibble()
for(p in 1:length(pkgs)){
  tmp <- cran_downloads(
    packages = pkgs[[p]]$name, 
    from = pkgs[[p]]$start_date, 
    to = "last-day"
  )
  logs <- bind_rows(logs, tmp)
}
rm(tmp, p)

```

# Packages on CRAN

## Row {height = 20%}

```{r}
#| content: valuebox
#| title: "Dashboard update"
list(
  icon = "calendar",
  color = "primary",
  value = Sys.time()
)
```

```{r}
#| content: valuebox
#| title: "Number of packages"
list(
  color = "primary",
  value = length(pkgs)
)
```

```{r}
#| content: valuebox
#| title: "Total downloads"
list(
  icon = "cloud-download",
  color = "primary",
  value = sum(logs$count, na.rm = TRUE)
)
```

## Row {height = 80%}

```{r}
#| fig-width: 15
#| echo: false

logs |>
  group_by(package) |>
  arrange(date) |>
  mutate(count = cumsum(count)) |>
  ungroup() |>
  ggplot(aes(x = date, y = count, colour = package)) +
  geom_line(linewidth = 1, alpha = .7) +
  scale_colour_solarized() +
  theme_solarized(light=FALSE) +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  labs(x = "Date", y = "Cumulative downloads", colour = "")
```


# Datasets

```{r, "setup dataset stats"}
#| echo: false
#| warning: false

library(zenstats)
source("era5_daily_ids.R")

stats_la <- deposit_stats(era5_daily_la, all_versions_only = TRUE, progress = FALSE)

stats_africa <- deposit_stats(era5_daily_africa, all_versions_only = TRUE, progress = FALSE)

stats_zonal_brazil <- deposit_stats(c(10036212, 10947952), all_versions_only = TRUE, progress = FALSE)

stats_road_dist <- deposit_stats(11400243, all_versions_only = TRUE, progress = FALSE)
```

## Row {height = 20%}

ERA5-Land Daily aggregates, Latin America

```{r}
#| content: valuebox
#| title: "Files"
list(
  icon = "files",
  color = "primary",
  value = nrow(stats_la)
)
```

```{r}
#| content: valuebox
#| title: "Views"
list(
  icon = "eye",
  color = "primary",
  value = sum(stats_la$views, na.rm = TRUE)
)
```

```{r}
#| content: valuebox
#| title: "Downloads"
list(
  icon = "cloud-download",
  color = "primary",
  value = sum(stats_la$downloads, na.rm = TRUE)
)
```

## Row {height = 20%}

ERA5-Land Daily aggregates, Africa

```{r}
#| content: valuebox
#| title: "Files"
list(
  icon = "files",
  color = "primary",
  value = nrow(stats_africa)
)
```

```{r}
#| content: valuebox
#| title: "Views"
list(
  icon = "eye",
  color = "primary",
  value = sum(stats_africa$views, na.rm = TRUE)
)
```

```{r}
#| content: valuebox
#| title: "Downloads"
list(
  icon = "cloud-download",
  color = "primary",
  value = sum(stats_africa$downloads, na.rm = TRUE)
)
```


## Row {height = 20%}

Zonal Statistics of Climate Indicators from ERA5-Land for Brazilian Municipalities

```{r}
#| content: valuebox
#| title: "Files"
list(
  icon = "files",
  color = "primary",
  value = nrow(stats_zonal_brazil)
)
```

```{r}
#| content: valuebox
#| title: "Views"
list(
  icon = "eye",
  color = "primary",
  value = sum(stats_zonal_brazil$views, na.rm = TRUE)
)
```

```{r}
#| content: valuebox
#| title: "Downloads"
list(
  icon = "cloud-download",
  color = "primary",
  value = sum(stats_zonal_brazil$downloads, na.rm = TRUE)
)
```

## Row {height = 20%}

Road distances and trip duration matrix for Brazilian municipalities

```{r}
#| content: valuebox
#| title: "Files"
list(
  icon = "files",
  color = "primary",
  value = nrow(stats_road_dist)
)
```

```{r}
#| content: valuebox
#| title: "Views"
list(
  icon = "eye",
  color = "primary",
  value = sum(stats_road_dist$views, na.rm = TRUE)
)
```

```{r}
#| content: valuebox
#| title: "Downloads"
list(
  icon = "cloud-download",
  color = "primary",
  value = sum(stats_road_dist$downloads, na.rm = TRUE)
)
```


